#!/usr/bin/env python3
"""Generate the committed Aurorae button SVGs from one state template."""

from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kde" / "aurorae" / "PrimerDark"

GLYPHS = {
    "close": '<path d="M12 12l10 10m0-10L12 22"/>',
    "minimize": '<path d="M11 19.5h12"/>',
    "maximize": '<rect x="11.5" y="11.5" width="11" height="11" rx="1.5"/>',
    "restore": '<path d="M13.5 14.5v-2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2"/><rect x="10.5" y="14.5" width="10" height="9" rx="1.5"/>',
    "alldesktops": '<circle cx="17" cy="17" r="5.5"/><circle cx="17" cy="17" r="1.5" fill="currentColor" stroke="none"/>',
    "keepabove": '<path d="M11.5 18.5 17 13l5.5 5.5M11.5 22 17 16.5 22.5 22"/>',
    "keepbelow": '<path d="m11.5 15.5 5.5 5.5 5.5-5.5M11.5 12l5.5 5.5 5.5-5.5"/>',
    "shade": '<path d="M11 12.5h12M12.5 21l4.5-4.5 4.5 4.5"/>',
    "help": '<circle cx="17" cy="17" r="7"/><path d="M14.5 14.5a2.6 2.6 0 1 1 3.4 2.5c-.9.35-.9 1.15-.9 1.5M17 21.5h.01"/>',
    "appmenu": '<path d="M11 12.5h12M11 17h12M11 21.5h12"/>',
}

STATES = [
    ("active-center", "#f0f6fc", None),
    ("hover-center", "#f0f6fc", "#212830"),
    ("pressed-center", "#ffffff", "#1f6feb"),
    ("inactive-center", "#9198a1", None),
    ("hover-inactive-center", "#f0f6fc", "#151b23"),
    ("pressed-inactive-center", "#ffffff", "#3d444d"),
    ("deactivated-center", "#656c76", None),
    ("deactivated-inactive-center", "#656c76", None),
]

HEADER = """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!-- Generated by scripts/generate-buttons.py; SPDX-License-Identifier: MIT -->
<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"272\" height=\"34\" viewBox=\"0 0 272 34\">
"""


def render(name: str, glyph: str) -> str:
    groups = []
    for index, (state, color, background) in enumerate(STATES):
        x = index * 34
        if name == "close" and state == "hover-center":
            background = "#da3633"
        elif name == "close" and state == "pressed-center":
            background = "#b62324"

        background_rect = ""
        if background:
            background_rect = (
                f'<rect x="2" y="2" width="30" height="30" rx="5" fill="{background}"/>'
            )

        groups.append(
            f'  <g id="{escape(state)}" transform="translate({x} 0)" color="{color}">\n'
            '    <rect width="34" height="34" fill="#000" fill-opacity="0.001"/>\n'
            f"    {background_rect}\n"
            f'    <g fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">{glyph}</g>\n'
            "  </g>"
        )
    return HEADER + "\n".join(groups) + "\n</svg>\n"


OUT.mkdir(parents=True, exist_ok=True)
for filename, glyph in GLYPHS.items():
    (OUT / f"{filename}.svg").write_text(render(filename, glyph), encoding="utf-8")
