#!/usr/bin/env python3
"""Generate the committed Spicetify theme for Spotify from the palette.

Spicetify turns each key of a theme's color.ini section into the custom
properties --spice-<key> (hex) and --spice-rgb-<key> (r,g,b), and swaps the
colors Spotify hardcodes in its style sheets for the eighteen base keys. The
Spotify client draws its dark appearance from Encore, its design system, whose
color sets (.encore-dark-theme and the .encore-*-set classes inside it) declare
the same 25 background, text, essential, and decorative properties. This script
writes integrations/spicetify/PrimerDark/color.ini with the base keys and the
Primer roles, and user.css, which redeclares every Encore dark set from those
roles. The theme only sets custom properties, so it never depends on Spotify's
generated class names.
With --check it fails when the committed files differ from the output.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "integrations" / "spicetify" / "PrimerDark"
TOKENS = json.loads((ROOT / "palette" / "primer-dark.json").read_text())["tokens"]
SCHEME = "Dark"
HEADER = "Generated by scripts/generate-spotify-theme.py from palette/primer-dark.json; SPDX-License-Identifier: MIT"


def p(token: str) -> str:
    group, name = token.split(".")
    return TOKENS[group][name].upper()


def rgb(color: str) -> tuple[int, int, int]:
    return tuple(int(color[i:i + 2], 16) for i in (1, 3, 5))


def mix(color: str, other: str, amount: float) -> str:
    """The color moved toward other by amount, as an opaque #RRGGBB."""
    channels = (round(c + (o - c) * amount) for c, o in zip(rgb(color), rgb(other)))
    return "#" + "".join(f"{c:02X}" for c in channels)


INSET = p("surface.inset")
FOCUS = p("accent.emphasis")
ACCENT = p("accent.foreground")
SUCCESS = p("status.success")
ATTENTION = p("status.attention")

# The Primer roles user.css reads, as extra color.ini keys. Filled controls
# keep their text readable: the blue, green, and red fills carry white text and
# darken on hover and press, green darkens from status.success until white
# text on it reaches a 4.5:1 contrast ratio, and the attention fill carries the
# inset color. The subdued status sets use the inset surfaces with the diff
# backgrounds of the same hue for hover and press.
ROLES = {
    "surface-inset": INSET,
    "surface-default": p("surface.default"),
    "surface-muted": p("surface.muted"),
    "surface-raised": p("surface.raised"),
    "surface-control": p("surface.control"),
    "border-default": p("border.default"),
    "border-subtle": p("border.subtle"),
    "border-emphasis": p("border.emphasis"),
    "fg-default": p("foreground.default"),
    "fg-subtle": p("foreground.subtle"),
    "fg-muted": p("foreground.muted"),
    "fg-on-emphasis": p("foreground.onEmphasis"),
    "accent-fg": ACCENT,
    "accent-emphasis": FOCUS,
    "accent-emphasis-hover": mix(FOCUS, INSET, 0.1),
    "accent-emphasis-press": mix(FOCUS, INSET, 0.2),
    "accent-inset": p("surface.accentInset"),
    "accent-inset-hover": p("diff.hunkNumber"),
    "accent-bright": p("syntax.string"),
    "success-fg": SUCCESS,
    "success-emphasis": mix(SUCCESS, INSET, 0.3),
    "success-emphasis-hover": mix(SUCCESS, INSET, 0.4),
    "success-emphasis-press": mix(SUCCESS, INSET, 0.5),
    "success-inset": p("surface.successInset"),
    "success-inset-hover": p("diff.addedWord"),
    "success-bright": p("status.successBright"),
    "attention-fg": ATTENTION,
    "attention-emphasis-hover": mix(ATTENTION, p("status.attentionBright"), 0.3),
    "attention-emphasis-press": mix(ATTENTION, INSET, 0.2),
    "attention-inset": p("surface.attentionInset"),
    "attention-inset-hover": p("syntax.markupChangedBackground"),
    "attention-bright": p("status.attentionBright"),
    "danger-fg": p("status.danger"),
    "danger-emphasis": p("status.dangerEmphasis"),
    "danger-emphasis-hover": p("status.dangerEmphasisHover"),
    "danger-emphasis-press": p("status.dangerEmphasisActive"),
    "danger-inset": p("surface.dangerInset"),
    "danger-inset-hover": p("syntax.markupDeletedBackground"),
    "danger-bright": p("status.dangerBright"),
}

# Spicetify's eighteen base keys, in its own order, with the Spotify role each
# one carries. Spicetify replaces Spotify's hardcoded hex colors with them.
BASE = {
    "text": ("fg-default", "headings and primary text"),
    "subtext": ("fg-muted", "secondary text, artist names, and metadata"),
    "main": ("surface-default", "main view background"),
    "main-elevated": ("surface-muted", "menus, cards, and other surfaces above the main view"),
    "highlight": ("surface-muted", "hover background in the main view"),
    "highlight-elevated": ("surface-raised", "hover background on elevated surfaces"),
    "sidebar": ("surface-inset", "app frame and black fills"),
    "player": ("surface-inset", "now playing bar"),
    "card": ("surface-raised", "card hover background"),
    "shadow": ("surface-inset", "drop shadows"),
    "selected-row": ("fg-default", "white overlay tint for selected rows and scrollbars"),
    "button": ("accent-fg", "accent fills and icons"),
    "button-active": ("accent-fg", "bright accent: play button, playing track, and active toggles"),
    "button-disabled": ("border-emphasis", "seek and volume bar tracks"),
    "tab-active": ("surface-control", "active tab and chip background"),
    "notification": ("accent-emphasis", "notification toasts"),
    "notification-error": ("danger-emphasis", "error toasts"),
    "misc": ("border-emphasis", "miscellaneous gray"),
}

SET_PROPERTIES = (
    "background-base", "background-highlight", "background-press",
    "background-elevated-base", "background-elevated-highlight", "background-elevated-press",
    "background-tinted-base", "background-tinted-highlight", "background-tinted-press",
    "text-base", "text-subdued", "text-bright-accent", "text-negative", "text-warning",
    "text-positive", "text-announcement",
    "essential-base", "essential-subdued", "essential-bright-accent", "essential-negative",
    "essential-warning", "essential-positive", "essential-announcement",
    "decorative-base", "decorative-subdued",
)


def var(role: str) -> str:
    assert role in ROLES, role
    return f"var(--spice-{role})"


def tint(role: str, alpha: float) -> str:
    assert role in ROLES, role
    return f"rgba(var(--spice-rgb-{role}), {alpha:g})"


def surface_set(base, highlight, press, elevated, elevated_highlight, elevated_press, subdued, divider):
    """A neutral Encore set: Primer surfaces with the full status palette."""
    return dict(zip(SET_PROPERTIES, (
        var(base), var(highlight), var(press),
        var(elevated), var(elevated_highlight), var(elevated_press),
        tint("border-emphasis", 0.2), tint("border-emphasis", 0.3), tint("border-emphasis", 0.4),
        var("fg-default"), var(subdued), var("accent-fg"), var("danger-fg"), var("attention-fg"),
        var("success-fg"), var("accent-fg"),
        var("fg-default"), var("border-emphasis"), var("accent-fg"), var("danger-fg"),
        var("attention-fg"), var("success-fg"), var("accent-emphasis"),
        var("fg-default"), var(divider),
    )))


def solid_set(base, highlight, press, foreground, divider):
    """A filled Encore set: one background ramp under one foreground color."""
    backgrounds = (base, highlight, press, highlight, highlight, press, base, base, base)
    return dict(zip(SET_PROPERTIES, (*map(var, backgrounds), *[var(foreground)] * 15, var(divider))))


APP_FRAME = surface_set(
    "surface-inset", "surface-muted", "surface-raised",
    "surface-muted", "surface-raised", "surface-default", "fg-muted", "border-subtle",
)

# Encore's dark sets, keyed by their selectors. The over-media set, which
# darkens artwork behind text, keeps Spotify's translucent black.
SETS = {
    ".encore-dark-theme,\n.encore-dark-theme .encore-base-set": surface_set(
        "surface-default", "surface-muted", "surface-inset",
        "surface-muted", "surface-raised", "surface-default", "fg-muted", "border-default",
    ),
    ".encore-dark-theme .encore-app-frame-set": APP_FRAME,
    ".encore-dark-theme .encore-muted-accent-set": APP_FRAME,
    ".encore-dark-theme .encore-inverted-dark-set": APP_FRAME,
    ".encore-dark-theme .encore-bright-accent-set": solid_set(
        "accent-emphasis", "accent-emphasis-hover", "accent-emphasis-press", "fg-on-emphasis", "accent-emphasis-press",
    ),
    ".encore-dark-theme .encore-announcement-set": solid_set(
        "accent-emphasis", "accent-emphasis-press", "accent-inset", "fg-on-emphasis", "accent-fg",
    ),
    ".encore-dark-theme .encore-announcement-subdued-set": solid_set(
        "accent-inset", "accent-inset-hover", "accent-inset-hover", "accent-bright", "accent-inset-hover",
    ),
    ".encore-dark-theme .encore-positive-set": solid_set(
        "success-emphasis", "success-emphasis-hover", "success-emphasis-press", "fg-on-emphasis", "success-emphasis-press",
    ),
    ".encore-dark-theme .encore-positive-subdued-set": solid_set(
        "success-inset", "success-inset-hover", "success-inset-hover", "success-bright", "success-inset-hover",
    ),
    ".encore-dark-theme .encore-negative-set": solid_set(
        "danger-emphasis", "danger-emphasis-hover", "danger-emphasis-press", "fg-on-emphasis", "danger-fg",
    ),
    ".encore-dark-theme .encore-negative-subdued-set": solid_set(
        "danger-inset", "danger-inset-hover", "danger-inset-hover", "danger-bright", "danger-inset-hover",
    ),
    ".encore-dark-theme .encore-warning-set": solid_set(
        "attention-fg", "attention-emphasis-hover", "attention-emphasis-press", "surface-inset", "attention-emphasis-press",
    ),
    ".encore-dark-theme .encore-warning-subdued-set": solid_set(
        "attention-inset", "attention-inset-hover", "attention-inset-hover", "attention-bright", "attention-inset-hover",
    ),
}

# The inverted sets are light surfaces, such as white pill buttons, so text
# keeps Primer's inset color on them and the accent darkens for contrast.
INVERTED = dict(zip(SET_PROPERTIES, (
    var("fg-default"), var("fg-on-emphasis"), var("fg-subtle"),
    var("fg-on-emphasis"), var("fg-on-emphasis"), var("fg-subtle"),
    var("fg-default"), var("fg-default"), var("fg-default"),
    var("surface-inset"), var("border-emphasis"), var("accent-emphasis-press"), *[var("surface-inset")] * 4,
    var("surface-inset"), var("border-emphasis"), var("accent-emphasis-press"), *[var("surface-inset")] * 4,
    var("surface-inset"), var("fg-subtle"),
)))
SETS[".encore-dark-theme .encore-inverted-set"] = INVERTED
SETS[".encore-dark-theme .encore-inverted-light-set"] = INVERTED

# Encore also passes each set's essential color to the set's children, for
# icons that follow their parent's text.
PARENTS = {
    ",\n".join(f"{part.strip()}>*" for part in selector.split(",")): properties["essential-base"]
    for selector, properties in SETS.items()
}


def render_ini() -> str:
    lines = [
        f"; {HEADER}",
        ";",
        "; The base keys are Spicetify's own color slots. Spicetify also swaps the",
        "; colors Spotify hardcodes in its style sheets for them. The role keys after",
        "; them are Primer Dark's palette roles, which user.css maps onto Spotify's",
        "; Encore color sets.",
        "",
        f"[{SCHEME}]",
    ]
    width = max(map(len, (*BASE, *ROLES)))
    for key, (role, description) in BASE.items():
        lines.append(f"; {description}")
        lines.append(f"{key:<{width}} = {ROLES[role][1:]}")
    lines.append("")
    for key, color in ROLES.items():
        lines.append(f"{key:<{width}} = {color[1:]}")
    return "\n".join(lines) + "\n"


def render_css() -> str:
    lines = [f"/* {HEADER} */", ""]
    for selector, properties in SETS.items():
        lines.append(selector + " {")
        lines += [f"    --{name}: {value};" for name, value in properties.items()]
        lines += ["}", ""]
    for selector, value in sorted(PARENTS.items()):
        lines += [selector + " {", f"    --parents-essential-base: {value};", "}", ""]
    return "\n".join(lines[:-1]) + "\n"


def main() -> int:
    outputs = {OUT / "color.ini": render_ini(), OUT / "user.css": render_css()}
    if sys.argv[1:] == ["--check"]:
        stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text() != content]
        for path in stale:
            print(f"{path.relative_to(ROOT)} is out of date; run scripts/generate-spotify-theme.py", file=sys.stderr)
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content)
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
