#!/usr/bin/env python3
"""Generate the committed Millennium theme for the Steam client from the palette.

Steam's desktop client (the 2023 UI) has no theme API and no color variables:
its style sheets in steamui/css set hardcoded colors on generated class names.
The theme therefore recolors those style sheets. For a given Steam build this
script reads every style sheet, keeps each declaration of a color longhand
(color, background-color, background-image, the border, outline, and shadow
colors, fill, stroke, and similar), and writes it again with Steam's colors
replaced by Primer roles:

- Steam's neutral grays and blue grays map to Primer surfaces, borders, and
  text by lightness, and its blue, green, red, orange, and yellow accents map to
  the Primer accent and status colors, with foreground and fill variants chosen
  by the property that uses them.
- Every such declaration is written again, mapped or not, in Steam's order,
  and every selector gains one :root level of specificity, so the copy keeps
  Steam's own cascade among those properties and wins over the original
  wherever Steam's style sheets load. The background, border, and outline
  shorthands are written as their color and image longhands only, so the copy
  never resets a width, style, position, or size, and Steam's root-relative
  image URLs are resolved against Steam's own origin.
- Keyframes with mapped colors are copied under a prefixed name, and the
  animation names that refer to them are rewritten to match.
- High-contrast and forced-colors media blocks are copied without mapping, so
  the accessibility modes keep Steam's colors.

Roles are written as rgb(var(--primer-<role>)), and colors.css, Millennium's
RootColors file, defines each role as raw RGB channels, so users can adjust
them in Millennium's theme editor. A palette change only regenerates colors.css.

Usage:
  generate-steam-theme.py [--steam-css DIR]  regenerate every file from a Steam
                                             installation (default
                                             ~/.local/share/Steam/steamui/css)
  generate-steam-theme.py --palette          regenerate colors.css and skin.json only
  generate-steam-theme.py --check            fail when colors.css or skin.json is
                                             stale or primer-dark.css is not a
                                             well-formed recolor of the roles
"""

import colorsys
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "integrations" / "steam" / "PrimerDark"
TOKENS = json.loads((ROOT / "palette" / "primer-dark.json").read_text())["tokens"]
DEFAULT_STEAM_CSS = Path.home() / ".local" / "share" / "Steam" / "steamui" / "css"
HEADER = "Generated by scripts/generate-steam-theme.py from palette/primer-dark.json; SPDX-License-Identifier: MIT"
KEYFRAME_PREFIX = "primer-dark-"


def p(token: str) -> str:
    group, name = token.split(".")
    return TOKENS[group][name].upper()


def rgb(color: str) -> tuple[int, int, int]:
    return tuple(int(color[i:i + 2], 16) for i in (1, 3, 5))


def mix(color: str, other: str, amount: float) -> str:
    channels = (round(c + (o - c) * amount) for c, o in zip(rgb(color), rgb(other)))
    return "#" + "".join(f"{c:02X}" for c in channels)


INSET = p("surface.inset")
FOCUS = p("accent.emphasis")
SUCCESS = p("status.success")

# The roles the recolored style sheets read, with the names Millennium's theme
# editor shows. Filled green controls darken status.success until white text
# on them reaches a 4.5:1 contrast ratio.
ROLES = {
    "inset": (INSET, "Inset", "Window frame and darkest fills"),
    "default": (p("surface.default"), "Background", "Main page background"),
    "muted": (p("surface.muted"), "Muted background", "Panels, sidebars, and dialogs"),
    "raised": (p("surface.raised"), "Raised background", "Cards and raised panels"),
    "control": (p("surface.control"), "Control", "Buttons and inputs"),
    "border": (p("border.default"), "Border", "Borders and separators"),
    "emphasis": (p("border.emphasis"), "Emphasis border", "Strong borders and disabled controls"),
    "fg-muted": (p("foreground.muted"), "Muted text", "Secondary text and icons"),
    "fg-subtle": (p("foreground.subtle"), "Subtle text", "Tertiary text"),
    "fg": (p("foreground.default"), "Text", "Primary text"),
    "accent-emphasis": (FOCUS, "Accent", "Accent fills and focus"),
    "accent-fg": (p("accent.foreground"), "Accent text", "Links and accent text"),
    "accent-bright": (p("syntax.constant"), "Bright accent text", "Light accent text"),
    "success-emphasis": (mix(SUCCESS, INSET, 0.3), "Success", "Play buttons and success fills"),
    "success-fg": (SUCCESS, "Success text", "Online status and success text"),
    "success-bright": (p("status.successBright"), "Bright success text", "Light success text"),
    "attention-emphasis": (p("status.attention"), "Attention", "Warning fills"),
    "attention-bright": (p("status.attentionBright"), "Attention text", "Warning text"),
    "severe": (p("status.severe"), "Severe", "Orange highlights"),
    "danger-emphasis": (p("status.dangerEmphasis"), "Danger", "Destructive fills"),
    "danger-fg": (p("status.danger"), "Danger text", "Error text"),
}

# Steam's neutrals by HSL lightness, from dark to light: the upper bound of each
# band and its role. #0E141B frames the window, #23262E fills dialogs and
# panels, #3D4450 fills controls, #67707B draws borders, #8B929A is muted text,
# and #DCDEDF to #FFFFFF is text.
NEUTRAL_BANDS = (
    (0.10, "inset"),
    (0.145, "default"),
    (0.18, "muted"),
    (0.235, "raised"),
    (0.30, "control"),
    (0.40, "border"),
    (0.52, "emphasis"),
    (0.64, "fg-muted"),
    (0.78, "fg-subtle"),
    (1.01, "fg"),
)

# Accent hues, as (lowest hue, highest hue, fill role, light fill role,
# text role, light text role); "light" means an HSL lightness of 0.6 or more.
ACCENTS = (
    (195, 228, "accent-emphasis", "accent-fg", "accent-fg", "accent-bright"),
    (95, 140, "success-emphasis", "success-bright", "success-fg", "success-bright"),
    (39, 62, "attention-emphasis", "attention-bright", "attention-bright", "attention-bright"),
    (16, 38, "severe", "severe", "severe", "severe"),
    (0, 15, "danger-emphasis", "danger-fg", "danger-fg", "danger-fg"),
    (345, 360, "danger-emphasis", "danger-fg", "danger-fg", "danger-fg"),
)

# Text-colored properties pick the text roles; every other property picks the
# fill roles.
TEXT_PROPERTIES = re.compile(
    r"^(color|fill|stroke|caret-color|-webkit-text-fill-color|-webkit-text-stroke-color|text-decoration-color|"
    r"text-emphasis-color|text-shadow|accent-color)$"
)
# The color longhands whose whole cascade the theme copies.
COLOR_LONGHANDS = re.compile(
    r"^(color|background-color|background-image|"
    r"border(-(top|right|bottom|left|block|inline)(-(start|end))?)?-color|outline-color|column-rule-color|"
    r"box-shadow|text-shadow|fill|stroke|caret-color|accent-color|scrollbar-color|"
    r"-webkit-text-fill-color|-webkit-text-stroke-color|text-decoration-color)$"
)
# Shorthands that set a color longhand; only that longhand is copied, so the
# copy never resets the widths, styles, positions, or sizes they also set.
BORDER_SHORTHANDS = re.compile(r"^(border(-(top|right|bottom|left|block|inline)(-(start|end))?)?|outline|column-rule)$")
NOT_COLORS = {
    "none", "hidden", "solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset",
    "thin", "medium", "thick", "auto", "inherit", "initial", "unset", "revert", "revert-layer",
}
ANIMATION_KEYWORDS = {
    "none", "infinite", "normal", "reverse", "alternate", "alternate-reverse", "forwards", "backwards",
    "both", "running", "paused", "linear", "ease", "ease-in", "ease-out", "ease-in-out", "step-start",
    "step-end", "inherit", "initial", "unset",
}
UNMAPPED_MEDIA = re.compile(r"prefers-contrast|forced-colors")
STEAM_ORIGIN = "https://steamloopback.host"

COLOR = re.compile(
    r"#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b"
    r"|\b(?:rgba?|hsla?)\([^()]*\)"
    r"|\b(?:white|black)\b"
)


def classify(color: tuple[int, int, int], text: bool) -> str | None:
    """The role for a Steam color, or None to keep Steam's color."""
    hue, lightness, saturation = colorsys.rgb_to_hls(*(c / 255 for c in color))
    hue *= 360
    if color == (0, 0, 0):
        return None
    if saturation < 0.06 or (195 <= hue <= 235 and saturation < 0.4):
        return next(role for limit, role in NEUTRAL_BANDS if lightness <= limit)
    if saturation < 0.45 or not 0.35 <= lightness <= 0.9:
        return None
    for low, high, fill, light_fill, foreground, light_foreground in ACCENTS:
        if low <= hue <= high:
            light = lightness >= 0.6
            return (light_foreground if light else foreground) if text else (light_fill if light else fill)
    return None


def parse_color(token: str) -> tuple[tuple[int, int, int], str | None] | None:
    """A color token as RGB channels and its alpha (None when opaque)."""
    lowered = token.lower()
    if lowered == "white":
        return (255, 255, 255), None
    if lowered == "black":
        return (0, 0, 0), None
    if lowered.startswith("#"):
        digits = lowered[1:]
        if len(digits) in (3, 4):
            digits = "".join(d * 2 for d in digits)
        channels = tuple(int(digits[i:i + 2], 16) for i in (0, 2, 4))
        alpha = None
        if len(digits) == 8 and digits[6:] != "ff":
            alpha = f"{int(digits[6:], 16) / 255:.3g}"
        return channels, alpha
    function, _, arguments = lowered.partition("(")
    parts = [part for part in re.split(r"[\s,/]+", arguments.rstrip(")").strip()) if part]
    if len(parts) not in (3, 4) or "var" in arguments or "calc" in arguments:
        return None
    try:
        if function.startswith("rgb"):
            channels = tuple(
                round(float(v[:-1]) * 2.55) if v.endswith("%") else round(float(v)) for v in parts[:3]
            )
        else:
            hue = float(parts[0].removesuffix("deg")) / 360
            saturation, lightness = (float(v.rstrip("%")) / 100 for v in parts[1:3])
            channels = tuple(round(c * 255) for c in colorsys.hls_to_rgb(hue, lightness, saturation))
        alpha = None
        if len(parts) == 4:
            value = float(parts[3][:-1]) / 100 if parts[3].endswith("%") else float(parts[3])
            alpha = None if value >= 1 else f"{value:.3g}"
    except ValueError:
        return None
    if not all(0 <= c <= 255 for c in channels):
        return None
    return channels, alpha


def map_value(value: str, text: bool) -> tuple[str, bool]:
    """The value with Steam's colors replaced by roles, and whether any changed."""
    changed = False

    def replace(match: re.Match) -> str:
        nonlocal changed
        parsed = parse_color(match.group(0))
        if parsed is None:
            return match.group(0)
        channels, alpha = parsed
        role = classify(channels, text)
        if role is None:
            return match.group(0)
        changed = True
        if alpha is None:
            return f"rgb(var(--primer-{role}))"
        return f"rgba(var(--primer-{role}), {alpha})"

    return COLOR.sub(replace, value), changed


def split_top(text: str, separator: str) -> list[str]:
    """Split on a separator outside parentheses, brackets, strings, and escapes."""
    parts, depth, quote, start, escaped = [], 0, None, 0, False
    for i, char in enumerate(text):
        if escaped:
            escaped = False
        elif char == "\\":
            escaped = True
        elif quote:
            if char == quote and text[i - 1] != "\\":
                quote = None
        elif char in "\"'":
            quote = char
        elif char in "([":
            depth += 1
        elif char in ")]":
            depth -= 1
        elif char == separator and depth == 0:
            parts.append(text[start:i])
            start = i + 1
    parts.append(text[start:])
    return parts


def parse(css: str, i: int = 0) -> tuple[list, int]:
    """Parse CSS into ("rule", selector, body), ("block", prelude, children),
    and ("raw", prelude, body) nodes, returning them and the end index. Steam's
    class names can contain escaped braces, so escapes are skipped."""
    nodes = []
    while i < len(css):
        while i < len(css) and css[i].isspace():
            i += 1
        if i >= len(css):
            break
        if css[i] == "}":
            return nodes, i + 1
        if css.startswith("/*", i):
            i = css.index("*/", i) + 2
            continue
        start, depth, quote = i, 0, None
        while i < len(css):
            char = css[i]
            if char == "\\":
                i += 2
                continue
            if quote:
                if char == quote and css[i - 1] != "\\":
                    quote = None
            elif char in "\"'":
                quote = char
            elif char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            elif depth == 0 and char in "{;":
                break
            i += 1
        prelude = css[start:i].strip()
        if i >= len(css) or css[i] == ";":
            i += 1
            continue
        i += 1
        if re.match(r"@(media|supports|container|layer|document)\b", prelude):
            children, i = parse(css, i)
            nodes.append(("block", prelude, children))
            continue
        body_start, depth, quote = i, 1, None
        while i < len(css) and depth:
            char = css[i]
            if char == "\\":
                i += 2
                continue
            if quote:
                if char == quote and css[i - 1] != "\\":
                    quote = None
            elif char in "\"'":
                quote = char
            elif char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
            i += 1
        body = css[body_start:i - 1]
        nodes.append(("raw" if prelude.startswith("@") else "rule", prelude, body))
    return nodes, i


def bump(selector: str) -> str:
    """The selector with one more class-level specificity, matching the same elements."""
    selector = selector.strip()
    if re.match(r"html(?![\w-])", selector):
        return "html:root" + selector[4:]
    if selector.startswith(":root"):
        return ":root" + selector
    return ":root " + selector


def declarations(body: str) -> list[tuple[str, str]]:
    result = []
    for declaration in split_top(body, ";"):
        name, colon, value = declaration.partition(":")
        if colon and name.strip():
            result.append((name.strip(), value.strip()))
    return result


def absolute_urls(value: str) -> str:
    """Resolve Steam's root-relative image URLs, which would otherwise resolve
    against the theme's own host."""
    return re.sub(r"url\((['\"]?)/(?!/)", lambda m: f"url({m.group(1)}{STEAM_ORIGIN}/", value)


def is_color_token(token: str) -> bool:
    if COLOR.fullmatch(token) or token.lower() in ("transparent", "currentcolor"):
        return True
    return re.fullmatch(r"[a-zA-Z]+", token) is not None and token.lower() not in NOT_COLORS


def is_image_token(token: str) -> bool:
    return re.match(r"(url|image-set|cross-fade|element|(-webkit-)?(repeating-)?(linear|radial|conic)-gradient)\(", token) is not None


def longhands(name: str, value: str) -> list[tuple[str, str]]:
    """The color longhands a declaration sets, with their values."""
    important = ""
    if value.lower().endswith("!important"):
        value, important = value[: -len("!important")].rstrip(), "!important"
    if name.startswith("--"):
        return [(name, value + important)] if COLOR.search(value) else []
    lowered = name.lower()
    if COLOR_LONGHANDS.match(lowered):
        return [(lowered, value + important)]
    if "var(" in value:
        return []
    if lowered == "background":
        layers = [split_top(layer.strip(), " ") for layer in split_top(value, ",")]
        images = [next((t for t in layer if is_image_token(t)), "none") for layer in layers]
        color = next((t for t in layers[-1] if t and is_color_token(t) and not is_image_token(t)), "transparent")
        if value.strip().lower() in ("inherit", "initial", "unset", "revert"):
            images, color = [value.strip()], value.strip()
        return [("background-color", color + important), ("background-image", ",".join(images) + important)]
    if BORDER_SHORTHANDS.match(lowered):
        tokens = [t for t in split_top(value, " ") if t]
        color = next((t for t in tokens if is_color_token(t)), "currentcolor")
        return [(f"{lowered}-color", color + important)]
    return []


class Recolor:
    def __init__(self, nodes: list):
        self.renamed = set()
        self.keyframes = []
        self.collect_keyframes(nodes, mapping=True)

    def collect_keyframes(self, nodes: list, mapping: bool):
        for kind, prelude, body in nodes:
            if kind == "block":
                self.collect_keyframes(body, mapping and not UNMAPPED_MEDIA.search(prelude))
            elif kind == "raw" and re.match(r"@(-webkit-)?keyframes\s", prelude) and mapping:
                name = prelude.split(None, 1)[1].strip()
                frames, _ = parse(body)
                lines, changed = [], False
                for _, frame_selector, frame_body in frames:
                    mapped = []
                    for property_name, value in declarations(frame_body):
                        new_value, did_change = map_value(value, bool(TEXT_PROPERTIES.match(property_name.lower())))
                        changed |= did_change
                        mapped.append(f"{property_name}:{absolute_urls(new_value)}")
                    lines.append(f"{frame_selector}{{{';'.join(mapped)}}}")
                if changed:
                    self.renamed.add(name)
                    keyword = prelude.split(None, 1)[0]
                    self.keyframes.append(f"{keyword} {KEYFRAME_PREFIX}{name}{{{''.join(lines)}}}")

    def animation_names(self, name: str, value: str) -> list[tuple[str, str]]:
        """The animation-name a declaration sets, with recolored keyframes renamed."""
        if not self.renamed:
            return []
        important = ""
        if value.lower().endswith("!important"):
            value, important = value[: -len("!important")].rstrip(), "!important"
        names = []
        for layer in split_top(value, ","):
            tokens = [t for t in split_top(layer.strip(), " ") if t]
            if name.lower().endswith("animation-name"):
                candidates = tokens
            else:
                candidates = [
                    t for t in tokens
                    if re.fullmatch(r"-?[a-zA-Z_][\w-]*", t) and t.lower() not in ANIMATION_KEYWORDS
                    and not re.fullmatch(r"[\d.]+m?s", t)
                ]
            if not candidates:
                names.append("none")
                continue
            names.append(KEYFRAME_PREFIX + candidates[0] if candidates[0] in self.renamed else candidates[0])
        prefix = "-webkit-" if name.lower().startswith("-webkit-") else ""
        return [(f"{prefix}animation-name", ",".join(names) + important)]

    def render(self, nodes: list, mapping: bool = True) -> list[str]:
        out = []
        for kind, prelude, body in nodes:
            if kind == "block":
                inner = self.render(body, mapping and not UNMAPPED_MEDIA.search(prelude))
                if inner:
                    out.append(f"{prelude}{{{''.join(inner)}}}")
            elif kind == "rule":
                kept = []
                for property_name, value in declarations(body):
                    if re.fullmatch(r"(-webkit-)?animation(-name)?", property_name.lower()):
                        kept += [f"{n}:{v}" for n, v in self.animation_names(property_name, value)]
                        continue
                    for longhand, longhand_value in longhands(property_name, value):
                        if mapping:
                            longhand_value, _ = map_value(longhand_value, bool(TEXT_PROPERTIES.match(longhand)))
                        kept.append(f"{longhand}:{absolute_urls(longhand_value)}")
                if kept:
                    selector = ",".join(bump(part) for part in split_top(prelude, ","))
                    out.append(f"{selector}{{{';'.join(kept)}}}")
        return out


def steam_version(css_dir: Path) -> str:
    manifest = css_dir.parents[1] / "package" / "steam_client_ubuntu12.manifest"
    match = re.search(r'"version"\s+"(\d+)"', manifest.read_text()) if manifest.is_file() else None
    return match.group(1) if match else "unknown"


def render_theme(css_dir: Path) -> str:
    # library.css is linked by the page; the shared chunk loads next, then the
    # feature chunks.
    files = sorted(css_dir.glob("*.css"), key=lambda f: (f.name != "library.css", "chunk~" not in f.name, f.name))
    sections = []
    for path in files:
        nodes, _ = parse(path.read_text(errors="replace"))
        recolor = Recolor(nodes)
        rules = recolor.render(nodes)
        if rules or recolor.keyframes:
            sections.append(f"/* steamui/css/{path.name} */\n" + "\n".join(recolor.keyframes + rules))
    return f"/* {HEADER}\n * Recolored from the style sheets of Steam client build {steam_version(css_dir)}. */\n" + "\n".join(sections) + "\n"


def audit(css: str) -> list[str]:
    """Problems in a generated theme: undefined roles, selectors without the
    specificity step, declarations outside the copied color longhands, and
    animations naming keyframes the theme does not define."""
    problems = [f"reads undefined role --primer-{role}"
                for role in sorted(set(re.findall(r"var\(--primer-([\w-]+)\)", css)) - set(ROLES))]
    nodes, _ = parse(css)
    keyframes = set()

    def walk(nodes: list):
        for kind, prelude, body in nodes:
            if kind == "block":
                walk(body)
            elif kind == "raw":
                if re.match(r"@(-webkit-)?keyframes\s", prelude):
                    keyframes.add(prelude.split(None, 1)[1].strip())
                else:
                    problems.append(f"unexpected at-rule {prelude[:60]}")
            else:
                for part in split_top(prelude, ","):
                    if not re.match(r"(:root|html:root)", part.strip()):
                        problems.append(f"selector without :root: {part.strip()[:80]}")
                for name, value in declarations(body):
                    if name.startswith("--") or COLOR_LONGHANDS.match(name):
                        continue
                    if re.fullmatch(r"(-webkit-)?animation-name", name):
                        names.update(n.strip() for n in value.removesuffix("!important").split(","))
                        continue
                    problems.append(f"unexpected property {name[:60]}")

    names = set()
    walk(nodes)
    problems += [f"animation-name {name} has no keyframes in the theme"
                 for name in sorted(names) if name.startswith(KEYFRAME_PREFIX) and name not in keyframes]
    return problems[:20]


def render_colors() -> str:
    lines = [":root {"]
    for role, (color, name, description) in ROLES.items():
        lines += [
            "    /*",
            f"     * @name {name}",
            f"     * @description {description}",
            "     */",
            f"    --primer-{role}: {', '.join(map(str, rgb(color)))};",
        ]
    return "\n".join(lines) + "\n}\n"


# Every desktop window Millennium's default patches theme; Big Picture mode
# and its Quick Access and Main menus keep Steam's look.
WINDOWS = (
    "^Steam$", "^OverlayBrowser_Browser$", "^SP Overlay:", "Supernav$", "^notificationtoasts_",
    "^SteamBrowser_Find$", "^OverlayTab\\d+_Find$", ".friendsui-container", "Menu$",
    ".ModalDialogPopup", ".FullModalOverlay",
)


def render_skin() -> str:
    skin = {
        "name": "Primer Dark",
        "author": "Reda Salmi",
        "description": "GitHub Primer Dark colors for the Steam desktop client.",
        "tags": ["Dark", "Minimal"],
        "github": {"owner": "redasalmi", "repo_name": "primer-dark-suite"},
        "RootColors": "colors.css",
        "Patches": [{"MatchRegexString": window, "TargetCss": "primer-dark.css"} for window in WINDOWS],
    }
    return json.dumps(skin, indent=4) + "\n"


def main() -> int:
    arguments = sys.argv[1:]
    palette_outputs = {OUT / "colors.css": render_colors(), OUT / "skin.json": render_skin()}
    if arguments == ["--check"]:
        errors = [
            f"{path.relative_to(ROOT)} is out of date; run scripts/generate-steam-theme.py --palette"
            for path, content in palette_outputs.items()
            if not path.is_file() or path.read_text() != content
        ]
        theme = OUT / "primer-dark.css"
        if not theme.is_file():
            errors.append(f"{theme.relative_to(ROOT)} is missing")
        else:
            errors += [f"{theme.relative_to(ROOT)}: {problem}" for problem in audit(theme.read_text())]
        for error in errors:
            print(error, file=sys.stderr)
        return 1 if errors else 0
    outputs = dict(palette_outputs)
    if arguments != ["--palette"]:
        css_dir = DEFAULT_STEAM_CSS
        if arguments[:1] == ["--steam-css"] and len(arguments) == 2:
            css_dir = Path(arguments[1])
        elif arguments:
            print(__doc__, file=sys.stderr)
            return 2
        if not css_dir.is_dir():
            print(f"{css_dir} not found; pass --steam-css with Steam's steamui/css directory", file=sys.stderr)
            return 1
        outputs[OUT / "primer-dark.css"] = render_theme(css_dir)
    OUT.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content)
        print(f"Wrote {path.relative_to(ROOT)} ({len(content.encode()) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
